version: '3'

networks:
  vpn_bridge:
    driver: bridge
    name: vpn_bridge
    driver_opts:
      com.docker.network.bridge.name: br-vpn

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
#    build:
#      context: .
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/ppp:/dev/ppp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.accept_redirects=0
      - net.ipv4.conf.default.send_redirects=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.send_redirects=0
      - net.ipv4.conf.eth0.rp_filter=0
    deploy:
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 8M
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - ${DOCKERS_DATA_ROOTDIR}:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    networks:
      - vpn_bridge
      